server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43306/blog?serverTimezone=Asia/Seoul
    username: laze
    password: laze1234
    
  jpa:
    open-in-view: true #영속성을 프리젠테이션 계층까지 가져가고, 트랜잭션은 Service 계층에서 종료, 그래서 Lazy Loading - 프록시 객체에 대해서 수행가능
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity를 만들때 변수명 그대로 테이블에, springname쓰면 카멜이 아니라 자동으로 언더바 표기법으로 바꿔줌
      use-new-id-generator-mappings: false #JPA의 기본 넘버링 전략을 따라가지 않는다는 뜻
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
    
  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
     